sudo: false
language: node_js
node_js:
- stable
env:
  global:
  - GH_USER_EMAIL="azuciao@gmail.com"
  - GH_USER_NAME="azu"
cache: yarn
before_install:
- npm install -g yarn@latest
jobs:
  include:
    # Deploy Docusaurus
    - stage: deploy
      node_js: stable
      if: branch = master AND type != pull_request
      install:
      - yarn install --frozen-lockfile
      - yarn run bootstrap --scope textlint-website
      before_script:
        - $(npm bin)/set-up-ssh --key "$encrypted_6407ccbe9d33_key" --iv "$encrypted_6407ccbe9d33_iv" --path-encrypted-key ".travis/textlint.github.io-deploykey.enc"
      script:
        - $(npm bin)/update-branch --commands "npm run website" --commit-message "Update Website [skip ci]" --directory "website/build/textlint" --distribution-branch "master" --distribution-repository "git@github.com:textlint/textlint.github.io.git" --source-branch "master"

